apiVersion: v1
kind: Service
metadata:
  name: OST
  namespace: namespace-workflow-1718229258394
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: OST
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80